-- ============================================================
-- KonektaYa · 2P · Número de recibo estable para los comprobantes de pago
-- ------------------------------------------------------------
-- Agrega una secuencia (receipt_seq) a paypal_orders para numerar los
-- comprobantes de forma consistente y bonita: KYA-000001, KYA-000002, ...
--
-- Es OPCIONAL: la app ya funciona sin correr esto (si la columna no existe,
-- el número del recibo se deriva del id de la orden de PayPal). Correrlo solo
-- mejora la numeración a una secuencia limpia.
--
-- Correr en Supabase → SQL Editor → Run. Idempotente.
-- ============================================================

-- Al agregar una columna IDENTITY a una tabla con filas, PostgreSQL rellena
-- las filas existentes con valores de la secuencia (1, 2, 3, ...) y las nuevas
-- órdenes continúan desde ahí automáticamente.
alter table public.paypal_orders
  add column if not exists receipt_seq bigint generated by default as identity;

-- Notas:
-- * RLS: la política existente paypal_orders_select_own ya permite que cada
--   usuario lea SUS propias órdenes, incluida esta nueva columna. No hay que
--   tocar políticas ni grants.
-- * Edge Function (paypal-credit): inserta con service_role y NO necesita
--   cambios; receipt_seq se autoasigna por ser IDENTITY.
